const SERVER_URL = 'http://localhost:3001';
export const QUERY_ENDPOINT = `${SERVER_URL}/query`;
export const CONFIG_ENDPOINT = `${SERVER_URL}/config`;
export const DELETE_ENDPOINT = `${SERVER_URL}/delete`;
export const COMMON_GREMLIN_ERROR = 'Invalid query. Please execute a query to get a set of vertices';
export const DELETE_GREMLIN_ERROR = 'Unable to run delete query.';
export const ACTIONS = {
  SET_NAME: 'SET_NAME',
  SET_HOST: 'SET_HOST',
  SET_PORT: 'SET_PORT',
  SET_QUERY: 'SET_QUERY',
  SET_ERROR: 'SET_ERROR',
  SET_NETWORK: 'SET_NETWORK',
  CLEAR_GRAPH: 'CLEAR_GRAPH',
  ADD_NODES: 'ADD_NODES',
  ADD_EDGES: 'ADD_EDGES',
  DELETE_EDGE: 'DELETE_EDGE',
  DELETE_NODE: 'DELETE_NODE',
  SET_SELECTED_NODE: 'SET_SELECTED_NODE',
  SET_SELECTED_EDGE: 'SET_SELECTED_EDGE',
  SET_CONSOLE_MODE: 'SET_CONSOLE_MODE',
  SET_MULTILINE_CONSOLE_MODE: 'SET_MULTILINE_CONSOLE_MODE',
  SET_IS_PHYSICS_ENABLED: 'SET_IS_PHYSICS_ENABLED',
  SET_IS_PHYSICS_ON_DRAG_ENABLED: 'SET_IS_PHYSICS_ON_DRAG_ENABLED',
  ADD_QUERY_HISTORY: 'ADD_QUERY_HISTORY',
  CLEAR_QUERY_HISTORY: 'CLEAR_QUERY_HISTORY',
  SET_NODE_LABELS: 'SET_NODE_LABELS',
  ADD_NODE_LABEL: 'ADD_NODE_LABEL',
  EDIT_NODE_LABEL: 'EDIT_NODE_LABEL',
  REMOVE_NODE_LABEL: 'REMOVE_NODE_LABEL',
  REFRESH_NODE_LABELS: 'REFRESH_NODE_LABELS',
  SET_NODE_LIMIT: 'SET_NODE_LIMIT',
  SET_TOGGLE_DRAWER: 'SET_TOGGLE_DRAWER',
  OPEN_DELETE: 'OPEN_DELETE',
  OPEN_PROPERTIES: 'OPEN_PROPERTIES',
  SET_CASCADE_DELETE: 'SET_CASCADE_DELETE'
  
};
